#+TITLE: Xmobar

* Xmobar

We are building two different bar for each screen.

Both screen contain the list of workspace and the current layout.

The Right screen contain mostly "useless so indispense" informations like CPU, RAM, Weather... the reason being that the far right part of my right screen is not really in my eightsight. I could switch those informations on the left part of the right screen eventually.

The left screen contain information that are in interest to me (so... the volume and the date for now)


** Installation steps

We compile xmobar to allow us to add code into the configuration.

1. make sure =stack= is installed (better installing it using their script @ [[https://docs.haskellstack.org/en/stable/install_and_upgrade/][Stack: Install guide]]
2. clone xmonad in this repository
3. run ~stack init~
4. We had to edit the generated config file to add some extra deps and the flags to allow all extensions
5. run ~stack install~
6. and finally, build and install our versions of the xmobar
#+begin_src sh

make clean
make
make install

#+end_src
7. The binaries are stored by default in =$HOME/.local/bin=
